### ISSUE TITLE
Issue when running deploy script

### ISSUE THREAD

**Issue by wiltipedia** [OElesin/querypal#1]
When attempting to deploy I am seeing the following error:
"Parameter validation failed:
Invalid length for parameter appId, value: 0, valid range: 1-inf"

**Comment by OElesin** [comment]
Hi @wiltipedia, thanks for pointing this out. This probably happened on [line 75](https://github.com/OElesin/querypal/blob/master/deploy.sh#L75).

Please check the Amplify stack was created. If not, this was probably due to missing GitHub token in the SSM parameter store with the key `/Querypal/Amplify/GitHubToken`. This is my fault. I should have pointed this out in the documentation.

To solve this, please create a GitHub token that can be used to create webhook and read-only deploy key

**Comment by wiltipedia** [comment]
Thanks!

I probably missed some steps, but was able to eventually get it to build in amplify and deploy

I am not seeing any of my Athena databases or tables in the GUI though. Is there some additional configuration I need to setup to see data?
